//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider.EntityModels.BackendModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BackendEntities : DbContext
    {
        public BackendEntities()
            : base("name=BackendEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<POIS> POIS { get; set; }
        public DbSet<PRODUCTCATEGORIES> PRODUCTCATEGORIES { get; set; }
        public DbSet<PRODUCTREVIEWS> PRODUCTREVIEWS { get; set; }
        public DbSet<PRODUCTS> PRODUCTS { get; set; }
        public DbSet<PRODUCTVARIANTATTRIBUTES> PRODUCTVARIANTATTRIBUTES { get; set; }
        public DbSet<PRODUCTVARIANTATTRIBUTEVALUES> PRODUCTVARIANTATTRIBUTEVALUES { get; set; }
        public DbSet<PRODUCTVARIANTS> PRODUCTVARIANTS { get; set; }
        public DbSet<USERS> USERS { get; set; }
        public DbSet<MEDIA> MEDIA { get; set; }
        public DbSet<MESSAGES> MESSAGES { get; set; }
        public DbSet<CUSTOMERS> CUSTOMERS { get; set; }
        public DbSet<ORDERITEMS> ORDERITEMS { get; set; }
        public DbSet<ORDERS> ORDERS { get; set; }
    }
}
