/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package games_set;

import games_set.games_interface.CGameManager;
import games_set.games_interface.CGames;
import games_set.games_interface.CSettings;


/**
 *
 * @author mato
 */
public class CGameSetApp extends javax.swing.JApplet {

    /**
     * Initializes the applet CGameSetApp
     */
    @Override
    public void init() {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CGameSetApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CGameSetApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CGameSetApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CGameSetApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the applet
         */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                public void run() {
                    CSettings.setGame(CGames.Sedma3);
                    CSettings.setNumberOfPlayers(4);
                    CSettings.setURL(getCodeBase());
                            
                    initComponents();
                    CSettings.setComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
            
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startGame = new javax.swing.JButton();
        exitGame = new javax.swing.JButton();
        guide = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        settingPanel = new javax.swing.JPanel();
        Sedma3Button = new javax.swing.JButton();
        gameNameLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        players = new javax.swing.JSpinner();
        difficulty = new javax.swing.JSpinner();
        width = new javax.swing.JSpinner();
        height = new javax.swing.JSpinner();
        Player0 = new javax.swing.JTextField();
        Player1 = new javax.swing.JTextField();
        computer0 = new javax.swing.JCheckBox();
        Player2 = new javax.swing.JTextField();
        computer1 = new javax.swing.JCheckBox();
        Player3 = new javax.swing.JTextField();
        computer2 = new javax.swing.JCheckBox();
        computer3 = new javax.swing.JCheckBox();
        Player4 = new javax.swing.JTextField();
        computer4 = new javax.swing.JCheckBox();
        Player5 = new javax.swing.JTextField();
        computer5 = new javax.swing.JCheckBox();
        Player6 = new javax.swing.JTextField();
        computer6 = new javax.swing.JCheckBox();
        Player7 = new javax.swing.JTextField();
        canvas1 = new CDisplay();
        credits = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 600));

        startGame.setText("Spusti hru");
        startGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameActionPerformed(evt);
            }
        });

        exitGame.setText("Ukonči hru");
        exitGame.setVisible(false);
        exitGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitGameActionPerformed(evt);
            }
        });

        guide.setText("Pomoc");

        Sedma3Button.setText("3 hore");
        Sedma3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sedma3ButtonActionPerformed(evt);
            }
        });

        gameNameLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        gameNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CSettings.setGameLabel(gameNameLabel);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Počet hráčov");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Obtiažnosť");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Veľkosť hracej plochy");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Šírka");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Výška");

        jLabel6.setText("Hráč 1");

        jLabel7.setText("Hráč 2");

        jLabel8.setText("Hráč 3");

        jLabel9.setText("Hráč 4");

        jLabel10.setText("Hráč 5");

        jLabel11.setText("Hráč 6");

        jLabel12.setText("Hráč 7");

        jLabel13.setText("Hráč 8");

        CSettings.setPlayerUI(players);
        players.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                playersStateChanged(evt);
            }
        });

        CSettings.setDifficultyUI(difficulty);
        difficulty.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                difficultyStateChanged(evt);
            }
        });

        CSettings.setWidthUI(width);
        width.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                widthStateChanged(evt);
            }
        });

        CSettings.setHeightUI(height);
        height.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                heightStateChanged(evt);
            }
        });

        CSettings.setPlayerNameUI(Player0, 0);
        Player0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player0ActionPerformed(evt);
            }
        });
        Player0.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Player0FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Player0FocusLost(evt);
            }
        });

        CSettings.setPlayerNameUI(Player1, 1);
        Player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player1ActionPerformed(evt);
            }
        });
        Player1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Player1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Player1FocusLost(evt);
            }
        });

        computer0.setSelected(true);
        computer0.setText("Počítač");
        CSettings.setComputerUI(computer0, 0);
        computer0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computer0ActionPerformed(evt);
            }
        });

        CSettings.setPlayerNameUI(Player2, 2);
        Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player2ActionPerformed(evt);
            }
        });
        Player2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Player2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Player2FocusLost(evt);
            }
        });

        computer1.setSelected(true);
        computer1.setText("Počítač");
        CSettings.setComputerUI(computer1, 1);
        computer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computer1ActionPerformed(evt);
            }
        });

        CSettings.setPlayerNameUI(Player3, 3);
        Player3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player3ActionPerformed(evt);
            }
        });
        Player3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Player3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Player3FocusLost(evt);
            }
        });

        computer2.setSelected(true);
        computer2.setText("Počítač");
        CSettings.setComputerUI(computer2, 2);
        computer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computer2ActionPerformed(evt);
            }
        });

        computer3.setSelected(true);
        computer3.setText("Počítač");
        CSettings.setComputerUI(computer3, 3);
        computer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computer3ActionPerformed(evt);
            }
        });

        CSettings.setPlayerNameUI(Player4, 4);
        Player4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player4ActionPerformed(evt);
            }
        });
        Player4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Player4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Player4FocusLost(evt);
            }
        });

        computer4.setSelected(true);
        computer4.setText("Počítač");
        CSettings.setComputerUI(computer4, 4);
        computer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computer4ActionPerformed(evt);
            }
        });

        CSettings.setPlayerNameUI(Player5, 5);
        Player5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player5ActionPerformed(evt);
            }
        });
        Player5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Player5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Player5FocusLost(evt);
            }
        });

        computer5.setSelected(true);
        computer5.setText("Počítač");
        CSettings.setComputerUI(computer5, 5);
        computer5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computer5ActionPerformed(evt);
            }
        });

        CSettings.setPlayerNameUI(Player6, 6);
        Player6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player6ActionPerformed(evt);
            }
        });
        Player6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Player6FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Player6FocusLost(evt);
            }
        });

        computer6.setSelected(true);
        computer6.setText("Počítač");
        CSettings.setComputerUI(computer6, 6);
        computer6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computer6ActionPerformed(evt);
            }
        });

        CSettings.setPlayerNameUI(Player7, 7);
        Player7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player7ActionPerformed(evt);
            }
        });
        Player7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Player7FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Player7FocusLost(evt);
            }
        });

        javax.swing.GroupLayout settingPanelLayout = new javax.swing.GroupLayout(settingPanel);
        settingPanel.setLayout(settingPanelLayout);
        settingPanelLayout.setHorizontalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(difficulty, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(players, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(settingPanelLayout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel4))
                            .addGroup(settingPanelLayout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel5))
                            .addGroup(settingPanelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(settingPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Player1))
                            .addGroup(settingPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Player0, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(settingPanelLayout.createSequentialGroup()
                                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Player2)
                                    .addComponent(Player3)
                                    .addComponent(Player4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Player5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Player6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Player7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(computer0, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(computer1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(computer2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(computer3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(computer4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(computer5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(computer6, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(gameNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(settingPanelLayout.createSequentialGroup()
                        .addComponent(Sedma3Button)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        settingPanelLayout.setVerticalGroup(
            settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Sedma3Button)
                .addGap(22, 22, 22)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(settingPanelLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(players, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(difficulty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(settingPanelLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(Player0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Player1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(computer0))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Player2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(computer1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Player3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(computer2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Player4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(computer3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Player5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(computer4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Player6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(computer5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(settingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Player7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(computer6)))
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        settingPanel.setBounds(10, 10, 580, 380);
        jLayeredPane1.add(settingPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        CGameManager.setDisplay((CDisplay)canvas1);
        canvas1.setVisible(false);
        canvas1.setPreferredSize(new java.awt.Dimension(400, 450));
        canvas1.setBounds(0, 0, 600, 450);
        jLayeredPane1.add(canvas1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        credits.setText("O Programe");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startGame)
                .addGap(18, 18, 18)
                .addComponent(exitGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(guide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(credits)
                .addGap(17, 17, 17))
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startGame)
                    .addComponent(exitGame)
                    .addComponent(guide)
                    .addComponent(credits))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void startGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameActionPerformed
        // TODO add your handling code here:
        CDisplay gameWindowDisplay=CGameManager.getDisplay();
        if(gameWindowDisplay==null) return;
        
        if(!CGameManager.gameInitialized())
        {  
            gameWindowDisplay.setVisible(true);
            
            settingPanel.setVisible(false);
            CSettings.startGame();
            
        }
        else
        {
            CGameManager.resetGame();
            gameWindowDisplay.repaint();
        }
        gameWindowDisplay.requestFocusInWindow();
        startGame.setText("Reštart");
        exitGame.setVisible(true);
        
        
    }//GEN-LAST:event_startGameActionPerformed

    private void exitGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitGameActionPerformed
        // TODO add your handling code here:
        CDisplay gameWindowDisplay=CGameManager.getDisplay();
        if(gameWindowDisplay==null) return;
        
        CGameManager.exitGame();
        gameWindowDisplay.setVisible(false);
        settingPanel.setVisible(true);
        startGame.setText("Spusti hru");
        exitGame.setVisible(false);
    }//GEN-LAST:event_exitGameActionPerformed

    private void Sedma3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sedma3ButtonActionPerformed
        // TODO add your handling code here:
        CSettings.setGame(CGames.Sedma3);
        gameNameLabel.setText(CSettings.getName());
        
    }//GEN-LAST:event_Sedma3ButtonActionPerformed

    private void playersStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_playersStateChanged
        // TODO add your handling code here:
        CSettings.setNumberOfPlayers((Integer)players.getValue());
    }//GEN-LAST:event_playersStateChanged

    private void difficultyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_difficultyStateChanged
        // TODO add your handling code here:
        CSettings.setDifficulty((Integer)difficulty.getValue());
    }//GEN-LAST:event_difficultyStateChanged

    private void widthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_widthStateChanged
        // TODO add your handling code here:
        CSettings.setSize((Integer)width.getValue(), CSettings.getHeight());
    }//GEN-LAST:event_widthStateChanged

    private void heightStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_heightStateChanged
        // TODO add your handling code here:
        CSettings.setSize(CSettings.getWidth(), (Integer)height.getValue());
    }//GEN-LAST:event_heightStateChanged

    private void Player0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player0ActionPerformed
        // TODO add your handling code here:
        CSettings.setPlayerName(0, Player0.getText());
    }//GEN-LAST:event_Player0ActionPerformed

    private void Player0FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Player0FocusLost
        // TODO add your handling code here:
        CSettings.setPlayerName(0, Player0.getText());
        
    }//GEN-LAST:event_Player0FocusLost

    private void Player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player1ActionPerformed
        // TODO add your handling code here:
        CSettings.setPlayerName(1, Player1.getText());
    }//GEN-LAST:event_Player1ActionPerformed

    private void Player1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Player1FocusLost
        // TODO add your handling code here:
        CSettings.setPlayerName(1, Player1.getText());
    }//GEN-LAST:event_Player1FocusLost

    private void Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player2ActionPerformed
        // TODO add your handling code here:
        CSettings.setPlayerName(2, Player2.getText());
    }//GEN-LAST:event_Player2ActionPerformed

    private void Player2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Player2FocusLost
        // TODO add your handling code here:
        CSettings.setPlayerName(2, Player2.getText());
    }//GEN-LAST:event_Player2FocusLost

    private void Player3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player3ActionPerformed
        // TODO add your handling code here:
        CSettings.setPlayerName(3, Player3.getText());
    }//GEN-LAST:event_Player3ActionPerformed

    private void Player3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Player3FocusLost
        // TODO add your handling code here:
        CSettings.setPlayerName(3, Player3.getText());
    }//GEN-LAST:event_Player3FocusLost

    private void Player4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player4ActionPerformed
        // TODO add your handling code here:
        CSettings.setPlayerName(4, Player4.getText());
    }//GEN-LAST:event_Player4ActionPerformed

    private void Player4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Player4FocusLost
        // TODO add your handling code here:
        CSettings.setPlayerName(4, Player4.getText());
    }//GEN-LAST:event_Player4FocusLost

    private void Player5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player5ActionPerformed
        // TODO add your handling code here:
        CSettings.setPlayerName(5, Player5.getText());
    }//GEN-LAST:event_Player5ActionPerformed

    private void Player5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Player5FocusLost
        // TODO add your handling code here:
        CSettings.setPlayerName(5, Player5.getText());
    }//GEN-LAST:event_Player5FocusLost

    private void Player6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player6ActionPerformed
        // TODO add your handling code here:
        CSettings.setPlayerName(6, Player6.getText());
    }//GEN-LAST:event_Player6ActionPerformed

    private void Player6FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Player6FocusLost
        // TODO add your handling code here:
        CSettings.setPlayerName(6, Player6.getText());
    }//GEN-LAST:event_Player6FocusLost

    private void Player7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player7ActionPerformed
        // TODO add your handling code here:
        CSettings.setPlayerName(7, Player7.getText());
    }//GEN-LAST:event_Player7ActionPerformed

    private void Player7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Player7FocusLost
        // TODO add your handling code here:
        CSettings.setPlayerName(7, Player7.getText());
    }//GEN-LAST:event_Player7FocusLost

    private void Player0FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Player0FocusGained
        // TODO add your handling code here:
        Player0.selectAll();
    }//GEN-LAST:event_Player0FocusGained

    private void Player1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Player1FocusGained
        // TODO add your handling code here:
        Player1.selectAll();
    }//GEN-LAST:event_Player1FocusGained

    private void Player2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Player2FocusGained
        // TODO add your handling code here:
        Player2.selectAll();
    }//GEN-LAST:event_Player2FocusGained

    private void Player3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Player3FocusGained
        // TODO add your handling code here:
        Player3.selectAll();
    }//GEN-LAST:event_Player3FocusGained

    private void Player4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Player4FocusGained
        // TODO add your handling code here:
        Player4.selectAll();
    }//GEN-LAST:event_Player4FocusGained

    private void Player5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Player5FocusGained
        // TODO add your handling code here:
        Player5.selectAll();
    }//GEN-LAST:event_Player5FocusGained

    private void Player6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Player6FocusGained
        // TODO add your handling code here:
        Player6.selectAll();
    }//GEN-LAST:event_Player6FocusGained

    private void Player7FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Player7FocusGained
        // TODO add your handling code here:
        Player7.selectAll();
    }//GEN-LAST:event_Player7FocusGained

    private void computer0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computer0ActionPerformed
        // TODO add your handling code here:
        CSettings.toggleComputer(1);
    }//GEN-LAST:event_computer0ActionPerformed

    private void computer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computer1ActionPerformed
        // TODO add your handling code here:
        CSettings.toggleComputer(2);
    }//GEN-LAST:event_computer1ActionPerformed

    private void computer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computer2ActionPerformed
        // TODO add your handling code here:
        CSettings.toggleComputer(3);
    }//GEN-LAST:event_computer2ActionPerformed

    private void computer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computer3ActionPerformed
        // TODO add your handling code here:
        CSettings.toggleComputer(4);
    }//GEN-LAST:event_computer3ActionPerformed

    private void computer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computer4ActionPerformed
        // TODO add your handling code here:
        CSettings.toggleComputer(5);
    }//GEN-LAST:event_computer4ActionPerformed

    private void computer5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computer5ActionPerformed
        // TODO add your handling code here:
        CSettings.toggleComputer(6);
    }//GEN-LAST:event_computer5ActionPerformed

    private void computer6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computer6ActionPerformed
        // TODO add your handling code here:
        CSettings.toggleComputer(7);
    }//GEN-LAST:event_computer6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Player0;
    private javax.swing.JTextField Player1;
    private javax.swing.JTextField Player2;
    private javax.swing.JTextField Player3;
    private javax.swing.JTextField Player4;
    private javax.swing.JTextField Player5;
    private javax.swing.JTextField Player6;
    private javax.swing.JTextField Player7;
    private javax.swing.JButton Sedma3Button;
    private java.awt.Canvas canvas1;
    private javax.swing.JCheckBox computer0;
    private javax.swing.JCheckBox computer1;
    private javax.swing.JCheckBox computer2;
    private javax.swing.JCheckBox computer3;
    private javax.swing.JCheckBox computer4;
    private javax.swing.JCheckBox computer5;
    private javax.swing.JCheckBox computer6;
    private javax.swing.JButton credits;
    private javax.swing.JSpinner difficulty;
    private javax.swing.JButton exitGame;
    private javax.swing.JLabel gameNameLabel;
    private javax.swing.JButton guide;
    private javax.swing.JSpinner height;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner players;
    private javax.swing.JPanel settingPanel;
    private javax.swing.JButton startGame;
    private javax.swing.JSpinner width;
    // End of variables declaration//GEN-END:variables

    
    
}
