//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider.EntityModels.FrontendModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FrontendEntities : DbContext
    {
        public FrontendEntities()
            : base("name=FrontendEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PRODUCTS> PRODUCTS { get; set; }
        public DbSet<ATTR> ATTRs { get; set; }
        public DbSet<ATTR_VALUES> ATTR_VALUES { get; set; }
        public DbSet<CATEGORIES> CATEGORIES { get; set; }
        public DbSet<PRODUCT_ATTRIBUTES> PRODUCT_ATTRIBUTES { get; set; }
        public DbSet<PRODUCT_TO_CATEGORY> PRODUCT_TO_CATEGORY { get; set; }
        public DbSet<IMAGES> IMAGES { get; set; }
        public DbSet<MENU> MENU { get; set; }
        public DbSet<REVIEWS> REVIEWS { get; set; }
        public DbSet<ORDER_ITEMS> ORDER_ITEMS { get; set; }
        public DbSet<ORDERS> ORDERS { get; set; }
        public DbSet<CUSTOMER_DETAILS> CUSTOMER_DETAILS { get; set; }
        public DbSet<CUSTOMERS> CUSTOMERS { get; set; }
        public DbSet<STATUSES> STATUSES { get; set; }
        public DbSet<COUNTRIES> COUNTRIES { get; set; }
    }
}
