/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AboutDialog.java
 *
 * Created on 26.7.2012, 13:21:41
 */
package labels;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author martinm
 */
public class AboutDialog extends JDialog {

    /** Creates new form AboutDialog */
    public AboutDialog(JFrame parent) {
        super(parent, "O programe", true);
        this.setBounds(parent.getX()+25, parent.getY()+25, 314, 350);
        initComponents();
        this.addWindowListener(new WindowAdapter(){

            @Override
            public void windowClosed(WindowEvent e) {
                super.windowClosed(e);
            }
            
        });
        String text=String.format("<html><div width='%d' align='justify'>%s</div></html>", 280,
                "Tento program slúži na tvorbu a tlač štítkov na obálky. "
                + "Štítky tlačí na formát A4 pričom je možné si vybrať, ktoré "
                + "štítky vytlačí a ktoré zostanú prázdne. Program je skonštruovaný "
                + "a testovaný na tlač štítkov na samolepiaci papier formátu A4 "
                + "(2x4 samolepiacich štítkov)");
        popis.setText(text);
        String licencia_text=String.format("<html><div width='%d' align='justify'>%s</div></html>", 280,
                "Tento program je voľne šíriteľný. Autor si vyhradzuje právo akokoľvek "
        + "manipulovať s programom.");
        licencia.setText(licencia_text);
    }
    
    private void windowClose(){
        this.setVisible(false);
    }
    
    public void openDialog(){
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        popis = new javax.swing.JLabel();
        licencia = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Adresné štítky");
        add(jLabel1);
        jLabel1.setBounds(0, 10, 294, 36);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(130, 280, 47, 23);

        jLabel2.setText("v 0.4.1");
        add(jLabel2);
        jLabel2.setBounds(260, 50, 35, 14);

        jLabel3.setText("Naprogramoval: Ing. Martin Mačaj");
        add(jLabel3);
        jLabel3.setBounds(10, 250, 254, 14);

        popis.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(popis);
        popis.setBounds(10, 85, 277, 100);

        licencia.setText("jLabel4");
        add(licencia);
        licencia.setBounds(10, 190, 280, 50);
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    windowClose();
}//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel licencia;
    private javax.swing.JLabel popis;
    // End of variables declaration//GEN-END:variables
}
